# Generated by Django 5.1.4 on 2024-12-24 22:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("punkweb_bb", "0007_boardprofile_bio"),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="punkweb_bb/badges/")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="boardprofile",
            name="badges",
            field=models.ManyToManyField(blank=True, null=True, to="punkweb_bb.badge"),
        ),
    ]
